server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:5173"
            allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
            allowedHeaders: ["*"]
            allowCredentials: true
      routes:
        - id: users
          uri: http://users-service:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: workouts
          uri: http://workouts-service:8082
          predicates:
            - Path=/api/workouts/**
          filters:
            - StripPrefix=1
        - id: progress
          uri: http://progress-service:8083
          predicates:
            - Path=/api/progress/**
          filters:
            - StripPrefix=1
