server:
  port: 8082

spring:
  application:
    name: workouts-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/fittrackr}

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
