server:
  port: 8083

spring:
  datasource:
    # Compose override’t deze via env, maar de default is alvast goed voor docker:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/progressdb}
    username: ${SPRING_DATASOURCE_USERNAME:progress}
    password: ${SPRING_DATASOURCE_PASSWORD:progress}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.hibernate.SQL: warn
    org.springframework: info
