server:
  port: 8083

spring:
  application:
    name: progress-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/progressdb}
    username: ${SPRING_DATASOURCE_USERNAME:progress}
    password: ${SPRING_DATASOURCE_PASSWORD:progress}
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
