name: CI - Build & Push to Docker Hub

on:
  push:
    branches: [ main ]   # pas aan als jouw default branch anders is
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_PREFIX: ${{ secrets.DOCKERHUB_USERNAME }}/apt-fittracker

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'
      - name: Run unit tests (all modules)
        run: mvn -fae -T 1C -B clean test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        svc:
          - { dir: 'users-service',    name: 'users-service' }
          - { dir: 'workouts-service', name: 'workouts-service' }
          - { dir: 'progress-service', name: 'progress-service' }
          - { dir: 'gateway',          name: 'gateway' }
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push ${{ matrix.svc.name }}
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.svc.dir }}
          file: ./${{ matrix.svc.dir }}/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_PREFIX }}-${{ matrix.svc.name }}:latest
            ${{ env.IMAGE_PREFIX }}-${{ matrix.svc.name }}:sha-${{ github.sha }}
          provenance: false
